spring.application.name=Eventra
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Eventra
spring.datasource.username=postgres
spring.datasource.password=asd@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=eventra-super-secret-key-change-this-in-production-min-256-bits
jwt.expiration=86400000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=TRACE