spring.application.name=Eventra
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

logging.level.org.springframework.web=info
logging.level.org.springframework.security=info

app.admin.key=${ADMIN_KEY}

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false

resend.api.key=${RESEND_API_KEY}